language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade setuptools pip pytest pytest-cov coverage codecov
  - pip install .
# command to run tests
script:
  - pytest -v --cov=fortdepend
after_success:
  - codecov
